### ISSUE TITLE
Initial version release

### ISSUE THREAD

**Issue by ragulka** [godaddy-wordpress/sake#1]
Original issue: https://github.com/skyverge/wc-plugins/issues/2049

### Goals

 - [x] Ensure that ~~grunt~~ _sake_ tasks to compile, build, zip, pre-release, and dev version replacement are available for any plugin, Woo, wp.org, or otherwise (look at potentially using separate packages for dev tasks and deployment tasks)
 - [x] Automatically do a composer install / update for plugins that require it
    - [x] Ensure we consider the individual plugin dev and non-dev composer requires, and document the task accordingly. See: https://getcomposer.org/doc/03-cli.md#update
    - [ ] Ensure we document the need for plugins to declare specific package versions where appropriate, so packages aren't updated to untested versions during deploy
 - [x] Ensure Framework v4 and v5 are compatible with scripts to build, pre-release, and deploy
 - [x] When using FW v5+, ensure framework version namespaces can be found / replaced as part of building a release zip

### Questions

- [ ] Discuss whether dev/pre-release version strategy (minor version bump + dev postfix) is accurate (added by Max, who wants to re-debate the pre-release versioning)
- [ ] Are there grunt tasks we can omit that are no longer needed?
- [ ] Are there any other [items on the roadmap](https://github.com/skyverge/wc-plugins/wiki/Grunt-Roadmap) that are immediate needs?

### Tasks

 - [x] Do any pre-flight checks, such as checking changelog format, **before** doing any tasks like version bump or changelog replacement, to ensure errors can be addressed and tasks re-run
- [x] Delete `phpunit.travis.xml` from the framework `lib/skyverge/` directory when bundling it.
- [x] Delete or exclude individual extension tests from a build
- [x] Ensure wc tested / requires version updates update the 3.2+ plugin header, not the readme
- [x] Refactor deploy task to only run needed tasks once. This is most important with building the zip file, as currently the deploy task builds a zip, then cleans the build directory (deleting the zip), and then re-compiling it, which is unnecessary. 

   With the previous issues in attaching a build to GH releases, the multiple build / zip tasks was the main issue. While the first zip used the right version, the re-created zip used the current version (dev version), **not** the deploy version, which broke attaching a release file. The grunt task looked for a zip to exist (it didn't), so it went to re-create it, and didn't set the deploy flag.

   SHA bd892d7fc351880136d49cbba5196091d21e7c1c and 2614922166c751bdee1ce671936b3133e19a5d9e put a temporary work-around in place to force the "deploy" flag during the "create release" task, but this can likely be streamlined / simplified as we don't use many of these tasks in stand-alone form.

- [x] `util.hasCoffeeFiles()` doesn't take into account a plugin like AvaTax, which includes a mixture of vanilla JS and CoffeeScript files. Once this is fixed, `util.getCoffeeMapFilesToClean()` should also get adjusted to make sure .map files are not deleted when they are needed.
- [x] compile only the assets that were actually changed in watch task. Currently, the watch task simply runs the full compile task, which will also include image optimization, etc - and takes more time than necessary. This makes PDF vouchers take forever when watching changes due to the bundled images.
- [x] Add ~~grunt-postcss and~~ autoprefixer and _cssnano_ to the compile task.
- [x] pre-release task should clean build directory after completion
- [x] ~~Bail on deploy early if the `WT_REPOS_PATH` doesn't contain the right destination directory for the plugin being deployed (:blame_max:) -- bail if the WT repo doesn't exist and prompt the user to clone it~~

   Alternatively, WT repo cloning should be updated to be cloned on the spot in a temp directory so it doesn't rely on the team member having cloned it at all. This would greatly reduce the number of errors we run into as well, not just because we forget to clone, but sometimes git screams on pull for no reason ¯\_(ツ)_/
- [x] Add prompt to select which issues in the WooThemes repo can be closed with the WooThemes commit push
- [x] WordPress and WooCommerce tested up to versions should automatically update on deploy - can most likely use the http-request npm package - Inspired by ZD Ticket 415527
- [x] Automate Trello step - see https://github.com/skyverge/wc-plugins/issues/394

### Move to roadmap:
- [ ] Add a debug / dry run mode to test / debug deploys with console logged output instead of running tasks.
 - [ ] Add the ability to easily add requires tasks / modules / etc for plugins depending on where distributed. For example, include `wp_deploy` for .org plugins
